// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_match_stats.proto

package matchstats

import (
	fmt "fmt"
	sslproto "github.com/RoboCup-SSL/ssl-go-tools/pkg/sslproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamColor int32

const (
	TeamColor_TEAM_UNKNOWN TeamColor = 0
	TeamColor_TEAM_YELLOW  TeamColor = 1
	TeamColor_TEAM_BLUE    TeamColor = 2
	TeamColor_TEAM_NONE    TeamColor = 3
)

var TeamColor_name = map[int32]string{
	0: "TEAM_UNKNOWN",
	1: "TEAM_YELLOW",
	2: "TEAM_BLUE",
	3: "TEAM_NONE",
}

var TeamColor_value = map[string]int32{
	"TEAM_UNKNOWN": 0,
	"TEAM_YELLOW":  1,
	"TEAM_BLUE":    2,
	"TEAM_NONE":    3,
}

func (x TeamColor) String() string {
	return proto.EnumName(TeamColor_name, int32(x))
}

func (TeamColor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{0}
}

type CommandType int32

const (
	CommandType_COMMAND_UNKNOWN         CommandType = 0
	CommandType_COMMAND_HALT            CommandType = 1
	CommandType_COMMAND_STOP            CommandType = 2
	CommandType_COMMAND_BALL_PLACEMENT  CommandType = 3
	CommandType_COMMAND_NORMAL_START    CommandType = 4
	CommandType_COMMAND_FORCE_START     CommandType = 5
	CommandType_COMMAND_DIRECT_FREE     CommandType = 6
	CommandType_COMMAND_INDIRECT_FREE   CommandType = 7
	CommandType_COMMAND_PREPARE_KICKOFF CommandType = 8
	CommandType_COMMAND_PREPARE_PENALTY CommandType = 9
	CommandType_COMMAND_TIMEOUT         CommandType = 10
	CommandType_COMMAND_GOAL            CommandType = 11
)

var CommandType_name = map[int32]string{
	0:  "COMMAND_UNKNOWN",
	1:  "COMMAND_HALT",
	2:  "COMMAND_STOP",
	3:  "COMMAND_BALL_PLACEMENT",
	4:  "COMMAND_NORMAL_START",
	5:  "COMMAND_FORCE_START",
	6:  "COMMAND_DIRECT_FREE",
	7:  "COMMAND_INDIRECT_FREE",
	8:  "COMMAND_PREPARE_KICKOFF",
	9:  "COMMAND_PREPARE_PENALTY",
	10: "COMMAND_TIMEOUT",
	11: "COMMAND_GOAL",
}

var CommandType_value = map[string]int32{
	"COMMAND_UNKNOWN":         0,
	"COMMAND_HALT":            1,
	"COMMAND_STOP":            2,
	"COMMAND_BALL_PLACEMENT":  3,
	"COMMAND_NORMAL_START":    4,
	"COMMAND_FORCE_START":     5,
	"COMMAND_DIRECT_FREE":     6,
	"COMMAND_INDIRECT_FREE":   7,
	"COMMAND_PREPARE_KICKOFF": 8,
	"COMMAND_PREPARE_PENALTY": 9,
	"COMMAND_TIMEOUT":         10,
	"COMMAND_GOAL":            11,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}

func (CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{1}
}

type StageType int32

const (
	StageType_STAGE_UNKNOWN                StageType = 0
	StageType_STAGE_NORMAL_FIRST_HALF_PRE  StageType = 1
	StageType_STAGE_NORMAL_FIRST_HALF      StageType = 2
	StageType_STAGE_NORMAL_HALF_TIME       StageType = 3
	StageType_STAGE_NORMAL_SECOND_HALF_PRE StageType = 4
	StageType_STAGE_NORMAL_SECOND_HALF     StageType = 5
	StageType_STAGE_EXTRA_TIME_BREAK       StageType = 6
	StageType_STAGE_EXTRA_FIRST_HALF_PRE   StageType = 7
	StageType_STAGE_EXTRA_FIRST_HALF       StageType = 8
	StageType_STAGE_EXTRA_HALF_TIME        StageType = 9
	StageType_STAGE_EXTRA_SECOND_HALF_PRE  StageType = 10
	StageType_STAGE_EXTRA_SECOND_HALF      StageType = 11
	StageType_STAGE_PENALTY_SHOOTOUT_BREAK StageType = 12
	StageType_STAGE_PENALTY_SHOOTOUT       StageType = 13
	StageType_STAGE_POST_GAME              StageType = 14
)

var StageType_name = map[int32]string{
	0:  "STAGE_UNKNOWN",
	1:  "STAGE_NORMAL_FIRST_HALF_PRE",
	2:  "STAGE_NORMAL_FIRST_HALF",
	3:  "STAGE_NORMAL_HALF_TIME",
	4:  "STAGE_NORMAL_SECOND_HALF_PRE",
	5:  "STAGE_NORMAL_SECOND_HALF",
	6:  "STAGE_EXTRA_TIME_BREAK",
	7:  "STAGE_EXTRA_FIRST_HALF_PRE",
	8:  "STAGE_EXTRA_FIRST_HALF",
	9:  "STAGE_EXTRA_HALF_TIME",
	10: "STAGE_EXTRA_SECOND_HALF_PRE",
	11: "STAGE_EXTRA_SECOND_HALF",
	12: "STAGE_PENALTY_SHOOTOUT_BREAK",
	13: "STAGE_PENALTY_SHOOTOUT",
	14: "STAGE_POST_GAME",
}

var StageType_value = map[string]int32{
	"STAGE_UNKNOWN":                0,
	"STAGE_NORMAL_FIRST_HALF_PRE":  1,
	"STAGE_NORMAL_FIRST_HALF":      2,
	"STAGE_NORMAL_HALF_TIME":       3,
	"STAGE_NORMAL_SECOND_HALF_PRE": 4,
	"STAGE_NORMAL_SECOND_HALF":     5,
	"STAGE_EXTRA_TIME_BREAK":       6,
	"STAGE_EXTRA_FIRST_HALF_PRE":   7,
	"STAGE_EXTRA_FIRST_HALF":       8,
	"STAGE_EXTRA_HALF_TIME":        9,
	"STAGE_EXTRA_SECOND_HALF_PRE":  10,
	"STAGE_EXTRA_SECOND_HALF":      11,
	"STAGE_PENALTY_SHOOTOUT_BREAK": 12,
	"STAGE_PENALTY_SHOOTOUT":       13,
	"STAGE_POST_GAME":              14,
}

func (x StageType) String() string {
	return proto.EnumName(StageType_name, int32(x))
}

func (StageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{2}
}

type GamePhaseType int32

const (
	GamePhaseType_PHASE_UNKNOWN         GamePhaseType = 0
	GamePhaseType_PHASE_RUNNING         GamePhaseType = 1
	GamePhaseType_PHASE_PREPARE_KICKOFF GamePhaseType = 2
	GamePhaseType_PHASE_PREPARE_PENALTY GamePhaseType = 3
	GamePhaseType_PHASE_STOP            GamePhaseType = 4
	GamePhaseType_PHASE_BALL_PLACEMENT  GamePhaseType = 5
	GamePhaseType_PHASE_TIMEOUT         GamePhaseType = 6
	GamePhaseType_PHASE_BREAK           GamePhaseType = 7
	GamePhaseType_PHASE_HALT            GamePhaseType = 8
	GamePhaseType_PHASE_POST_GAME       GamePhaseType = 9
)

var GamePhaseType_name = map[int32]string{
	0: "PHASE_UNKNOWN",
	1: "PHASE_RUNNING",
	2: "PHASE_PREPARE_KICKOFF",
	3: "PHASE_PREPARE_PENALTY",
	4: "PHASE_STOP",
	5: "PHASE_BALL_PLACEMENT",
	6: "PHASE_TIMEOUT",
	7: "PHASE_BREAK",
	8: "PHASE_HALT",
	9: "PHASE_POST_GAME",
}

var GamePhaseType_value = map[string]int32{
	"PHASE_UNKNOWN":         0,
	"PHASE_RUNNING":         1,
	"PHASE_PREPARE_KICKOFF": 2,
	"PHASE_PREPARE_PENALTY": 3,
	"PHASE_STOP":            4,
	"PHASE_BALL_PLACEMENT":  5,
	"PHASE_TIMEOUT":         6,
	"PHASE_BREAK":           7,
	"PHASE_HALT":            8,
	"PHASE_POST_GAME":       9,
}

func (x GamePhaseType) String() string {
	return proto.EnumName(GamePhaseType_name, int32(x))
}

func (GamePhaseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{3}
}

type Command struct {
	Type                 CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=CommandType" json:"type,omitempty"`
	ForTeam              TeamColor   `protobuf:"varint,2,opt,name=for_team,json=forTeam,proto3,enum=TeamColor" json:"for_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetType() CommandType {
	if m != nil {
		return m.Type
	}
	return CommandType_COMMAND_UNKNOWN
}

func (m *Command) GetForTeam() TeamColor {
	if m != nil {
		return m.ForTeam
	}
	return TeamColor_TEAM_UNKNOWN
}

type GamePhase struct {
	StartTime            uint64                `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              uint64                `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration             uint32                `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Type                 GamePhaseType         `protobuf:"varint,4,opt,name=type,proto3,enum=GamePhaseType" json:"type,omitempty"`
	CommandEntry         *Command              `protobuf:"bytes,5,opt,name=command_entry,json=commandEntry,proto3" json:"command_entry,omitempty"`
	CommandExit          *Command              `protobuf:"bytes,6,opt,name=command_exit,json=commandExit,proto3" json:"command_exit,omitempty"`
	ForTeam              TeamColor             `protobuf:"varint,7,opt,name=for_team,json=forTeam,proto3,enum=TeamColor" json:"for_team,omitempty"`
	GameEventsEntry      []*sslproto.GameEvent `protobuf:"bytes,8,rep,name=game_events_entry,json=gameEventsEntry,proto3" json:"game_events_entry,omitempty"`
	GameEventsExit       []*sslproto.GameEvent `protobuf:"bytes,9,rep,name=game_events_exit,json=gameEventsExit,proto3" json:"game_events_exit,omitempty"`
	NextCommandProposed  *Command              `protobuf:"bytes,10,opt,name=next_command_proposed,json=nextCommandProposed,proto3" json:"next_command_proposed,omitempty"`
	Stage                StageType             `protobuf:"varint,11,opt,name=stage,proto3,enum=StageType" json:"stage,omitempty"`
	StageTimeLeftEntry   int32                 `protobuf:"zigzag32,12,opt,name=stage_time_left_entry,json=stageTimeLeftEntry,proto3" json:"stage_time_left_entry,omitempty"`
	StageTimeLeftExit    int32                 `protobuf:"zigzag32,13,opt,name=stage_time_left_exit,json=stageTimeLeftExit,proto3" json:"stage_time_left_exit,omitempty"`
	CommandPrev          *Command              `protobuf:"bytes,14,opt,name=command_prev,json=commandPrev,proto3" json:"command_prev,omitempty"`
	GameEventsTimed      []*GameEventTimed     `protobuf:"bytes,15,rep,name=game_events_timed,json=gameEventsTimed,proto3" json:"game_events_timed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GamePhase) Reset()         { *m = GamePhase{} }
func (m *GamePhase) String() string { return proto.CompactTextString(m) }
func (*GamePhase) ProtoMessage()    {}
func (*GamePhase) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{1}
}

func (m *GamePhase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePhase.Unmarshal(m, b)
}
func (m *GamePhase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePhase.Marshal(b, m, deterministic)
}
func (m *GamePhase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePhase.Merge(m, src)
}
func (m *GamePhase) XXX_Size() int {
	return xxx_messageInfo_GamePhase.Size(m)
}
func (m *GamePhase) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePhase.DiscardUnknown(m)
}

var xxx_messageInfo_GamePhase proto.InternalMessageInfo

func (m *GamePhase) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GamePhase) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *GamePhase) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *GamePhase) GetType() GamePhaseType {
	if m != nil {
		return m.Type
	}
	return GamePhaseType_PHASE_UNKNOWN
}

func (m *GamePhase) GetCommandEntry() *Command {
	if m != nil {
		return m.CommandEntry
	}
	return nil
}

func (m *GamePhase) GetCommandExit() *Command {
	if m != nil {
		return m.CommandExit
	}
	return nil
}

func (m *GamePhase) GetForTeam() TeamColor {
	if m != nil {
		return m.ForTeam
	}
	return TeamColor_TEAM_UNKNOWN
}

func (m *GamePhase) GetGameEventsEntry() []*sslproto.GameEvent {
	if m != nil {
		return m.GameEventsEntry
	}
	return nil
}

func (m *GamePhase) GetGameEventsExit() []*sslproto.GameEvent {
	if m != nil {
		return m.GameEventsExit
	}
	return nil
}

func (m *GamePhase) GetNextCommandProposed() *Command {
	if m != nil {
		return m.NextCommandProposed
	}
	return nil
}

func (m *GamePhase) GetStage() StageType {
	if m != nil {
		return m.Stage
	}
	return StageType_STAGE_UNKNOWN
}

func (m *GamePhase) GetStageTimeLeftEntry() int32 {
	if m != nil {
		return m.StageTimeLeftEntry
	}
	return 0
}

func (m *GamePhase) GetStageTimeLeftExit() int32 {
	if m != nil {
		return m.StageTimeLeftExit
	}
	return 0
}

func (m *GamePhase) GetCommandPrev() *Command {
	if m != nil {
		return m.CommandPrev
	}
	return nil
}

func (m *GamePhase) GetGameEventsTimed() []*GameEventTimed {
	if m != nil {
		return m.GameEventsTimed
	}
	return nil
}

type GameEventTimed struct {
	GameEvent            *sslproto.GameEvent `protobuf:"bytes,1,opt,name=game_event,json=gameEvent,proto3" json:"game_event,omitempty"`
	Timestamp            uint64              `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Withdrawn            bool                `protobuf:"varint,3,opt,name=withdrawn,proto3" json:"withdrawn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GameEventTimed) Reset()         { *m = GameEventTimed{} }
func (m *GameEventTimed) String() string { return proto.CompactTextString(m) }
func (*GameEventTimed) ProtoMessage()    {}
func (*GameEventTimed) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{2}
}

func (m *GameEventTimed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEventTimed.Unmarshal(m, b)
}
func (m *GameEventTimed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEventTimed.Marshal(b, m, deterministic)
}
func (m *GameEventTimed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEventTimed.Merge(m, src)
}
func (m *GameEventTimed) XXX_Size() int {
	return xxx_messageInfo_GameEventTimed.Size(m)
}
func (m *GameEventTimed) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEventTimed.DiscardUnknown(m)
}

var xxx_messageInfo_GameEventTimed proto.InternalMessageInfo

func (m *GameEventTimed) GetGameEvent() *sslproto.GameEvent {
	if m != nil {
		return m.GameEvent
	}
	return nil
}

func (m *GameEventTimed) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GameEventTimed) GetWithdrawn() bool {
	if m != nil {
		return m.Withdrawn
	}
	return false
}

type TeamStats struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Goals                uint32   `protobuf:"varint,2,opt,name=goals,proto3" json:"goals,omitempty"`
	Fouls                uint32   `protobuf:"varint,3,opt,name=fouls,proto3" json:"fouls,omitempty"`
	YellowCards          uint32   `protobuf:"varint,4,opt,name=yellow_cards,json=yellowCards,proto3" json:"yellow_cards,omitempty"`
	RedCards             uint32   `protobuf:"varint,5,opt,name=red_cards,json=redCards,proto3" json:"red_cards,omitempty"`
	TimeoutTime          uint32   `protobuf:"varint,6,opt,name=timeout_time,json=timeoutTime,proto3" json:"timeout_time,omitempty"`
	TimeoutsTaken        uint32   `protobuf:"varint,7,opt,name=timeouts_taken,json=timeoutsTaken,proto3" json:"timeouts_taken,omitempty"`
	TimeoutsLeft         uint32   `protobuf:"varint,14,opt,name=timeouts_left,json=timeoutsLeft,proto3" json:"timeouts_left,omitempty"`
	PenaltyShotsTotal    uint32   `protobuf:"varint,8,opt,name=penalty_shots_total,json=penaltyShotsTotal,proto3" json:"penalty_shots_total,omitempty"`
	PenaltyShotsSuccess  uint32   `protobuf:"varint,9,opt,name=penalty_shots_success,json=penaltyShotsSuccess,proto3" json:"penalty_shots_success,omitempty"`
	ConcededGoals        uint32   `protobuf:"varint,10,opt,name=conceded_goals,json=concededGoals,proto3" json:"conceded_goals,omitempty"`
	BallPlacementTime    uint32   `protobuf:"varint,11,opt,name=ball_placement_time,json=ballPlacementTime,proto3" json:"ball_placement_time,omitempty"`
	BallPlacements       uint32   `protobuf:"varint,12,opt,name=ball_placements,json=ballPlacements,proto3" json:"ball_placements,omitempty"`
	MaxActiveYellowCards uint32   `protobuf:"varint,13,opt,name=max_active_yellow_cards,json=maxActiveYellowCards,proto3" json:"max_active_yellow_cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamStats) Reset()         { *m = TeamStats{} }
func (m *TeamStats) String() string { return proto.CompactTextString(m) }
func (*TeamStats) ProtoMessage()    {}
func (*TeamStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{3}
}

func (m *TeamStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStats.Unmarshal(m, b)
}
func (m *TeamStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStats.Marshal(b, m, deterministic)
}
func (m *TeamStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStats.Merge(m, src)
}
func (m *TeamStats) XXX_Size() int {
	return xxx_messageInfo_TeamStats.Size(m)
}
func (m *TeamStats) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStats.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStats proto.InternalMessageInfo

func (m *TeamStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeamStats) GetGoals() uint32 {
	if m != nil {
		return m.Goals
	}
	return 0
}

func (m *TeamStats) GetFouls() uint32 {
	if m != nil {
		return m.Fouls
	}
	return 0
}

func (m *TeamStats) GetYellowCards() uint32 {
	if m != nil {
		return m.YellowCards
	}
	return 0
}

func (m *TeamStats) GetRedCards() uint32 {
	if m != nil {
		return m.RedCards
	}
	return 0
}

func (m *TeamStats) GetTimeoutTime() uint32 {
	if m != nil {
		return m.TimeoutTime
	}
	return 0
}

func (m *TeamStats) GetTimeoutsTaken() uint32 {
	if m != nil {
		return m.TimeoutsTaken
	}
	return 0
}

func (m *TeamStats) GetTimeoutsLeft() uint32 {
	if m != nil {
		return m.TimeoutsLeft
	}
	return 0
}

func (m *TeamStats) GetPenaltyShotsTotal() uint32 {
	if m != nil {
		return m.PenaltyShotsTotal
	}
	return 0
}

func (m *TeamStats) GetPenaltyShotsSuccess() uint32 {
	if m != nil {
		return m.PenaltyShotsSuccess
	}
	return 0
}

func (m *TeamStats) GetConcededGoals() uint32 {
	if m != nil {
		return m.ConcededGoals
	}
	return 0
}

func (m *TeamStats) GetBallPlacementTime() uint32 {
	if m != nil {
		return m.BallPlacementTime
	}
	return 0
}

func (m *TeamStats) GetBallPlacements() uint32 {
	if m != nil {
		return m.BallPlacements
	}
	return 0
}

func (m *TeamStats) GetMaxActiveYellowCards() uint32 {
	if m != nil {
		return m.MaxActiveYellowCards
	}
	return 0
}

type DurationStats struct {
	Duration             uint32   `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	DurationMin          uint32   `protobuf:"varint,2,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	DurationMax          uint32   `protobuf:"varint,3,opt,name=duration_max,json=durationMax,proto3" json:"duration_max,omitempty"`
	DurationMedian       uint32   `protobuf:"varint,4,opt,name=duration_median,json=durationMedian,proto3" json:"duration_median,omitempty"`
	DurationAvg          uint32   `protobuf:"varint,5,opt,name=duration_avg,json=durationAvg,proto3" json:"duration_avg,omitempty"`
	DurationRelative     float32  `protobuf:"fixed32,6,opt,name=duration_relative,json=durationRelative,proto3" json:"duration_relative,omitempty"`
	Count                uint32   `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DurationStats) Reset()         { *m = DurationStats{} }
func (m *DurationStats) String() string { return proto.CompactTextString(m) }
func (*DurationStats) ProtoMessage()    {}
func (*DurationStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{4}
}

func (m *DurationStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DurationStats.Unmarshal(m, b)
}
func (m *DurationStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DurationStats.Marshal(b, m, deterministic)
}
func (m *DurationStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DurationStats.Merge(m, src)
}
func (m *DurationStats) XXX_Size() int {
	return xxx_messageInfo_DurationStats.Size(m)
}
func (m *DurationStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DurationStats.DiscardUnknown(m)
}

var xxx_messageInfo_DurationStats proto.InternalMessageInfo

func (m *DurationStats) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *DurationStats) GetDurationMin() uint32 {
	if m != nil {
		return m.DurationMin
	}
	return 0
}

func (m *DurationStats) GetDurationMax() uint32 {
	if m != nil {
		return m.DurationMax
	}
	return 0
}

func (m *DurationStats) GetDurationMedian() uint32 {
	if m != nil {
		return m.DurationMedian
	}
	return 0
}

func (m *DurationStats) GetDurationAvg() uint32 {
	if m != nil {
		return m.DurationAvg
	}
	return 0
}

func (m *DurationStats) GetDurationRelative() float32 {
	if m != nil {
		return m.DurationRelative
	}
	return 0
}

func (m *DurationStats) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type MatchStats struct {
	Name                 string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MatchDuration        uint32                    `protobuf:"varint,2,opt,name=match_duration,json=matchDuration,proto3" json:"match_duration,omitempty"`
	StartTime            uint64                    `protobuf:"varint,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	GamePhases           []*GamePhase              `protobuf:"bytes,3,rep,name=game_phases,json=gamePhases,proto3" json:"game_phases,omitempty"`
	ExtraTime            bool                      `protobuf:"varint,4,opt,name=extra_time,json=extraTime,proto3" json:"extra_time,omitempty"`
	Shootout             bool                      `protobuf:"varint,5,opt,name=shootout,proto3" json:"shootout,omitempty"`
	TeamStatsYellow      *TeamStats                `protobuf:"bytes,6,opt,name=team_stats_yellow,json=teamStatsYellow,proto3" json:"team_stats_yellow,omitempty"`
	TeamStatsBlue        *TeamStats                `protobuf:"bytes,7,opt,name=team_stats_blue,json=teamStatsBlue,proto3" json:"team_stats_blue,omitempty"`
	GamePhaseDurations   map[string]*DurationStats `protobuf:"bytes,8,rep,name=game_phase_durations,json=gamePhaseDurations,proto3" json:"game_phase_durations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	GameEventDurations   map[string]*DurationStats `protobuf:"bytes,9,rep,name=game_event_durations,json=gameEventDurations,proto3" json:"game_event_durations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MatchStats) Reset()         { *m = MatchStats{} }
func (m *MatchStats) String() string { return proto.CompactTextString(m) }
func (*MatchStats) ProtoMessage()    {}
func (*MatchStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{5}
}

func (m *MatchStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchStats.Unmarshal(m, b)
}
func (m *MatchStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchStats.Marshal(b, m, deterministic)
}
func (m *MatchStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchStats.Merge(m, src)
}
func (m *MatchStats) XXX_Size() int {
	return xxx_messageInfo_MatchStats.Size(m)
}
func (m *MatchStats) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchStats.DiscardUnknown(m)
}

var xxx_messageInfo_MatchStats proto.InternalMessageInfo

func (m *MatchStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MatchStats) GetMatchDuration() uint32 {
	if m != nil {
		return m.MatchDuration
	}
	return 0
}

func (m *MatchStats) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *MatchStats) GetGamePhases() []*GamePhase {
	if m != nil {
		return m.GamePhases
	}
	return nil
}

func (m *MatchStats) GetExtraTime() bool {
	if m != nil {
		return m.ExtraTime
	}
	return false
}

func (m *MatchStats) GetShootout() bool {
	if m != nil {
		return m.Shootout
	}
	return false
}

func (m *MatchStats) GetTeamStatsYellow() *TeamStats {
	if m != nil {
		return m.TeamStatsYellow
	}
	return nil
}

func (m *MatchStats) GetTeamStatsBlue() *TeamStats {
	if m != nil {
		return m.TeamStatsBlue
	}
	return nil
}

func (m *MatchStats) GetGamePhaseDurations() map[string]*DurationStats {
	if m != nil {
		return m.GamePhaseDurations
	}
	return nil
}

func (m *MatchStats) GetGameEventDurations() map[string]*DurationStats {
	if m != nil {
		return m.GameEventDurations
	}
	return nil
}

type MatchStatsCollection struct {
	MatchStats           []*MatchStats             `protobuf:"bytes,1,rep,name=match_stats,json=matchStats,proto3" json:"match_stats,omitempty"`
	TeamStats            map[string]*TeamStats     `protobuf:"bytes,2,rep,name=team_stats,json=teamStats,proto3" json:"team_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	GamePhaseDurations   map[string]*DurationStats `protobuf:"bytes,3,rep,name=game_phase_durations,json=gamePhaseDurations,proto3" json:"game_phase_durations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	GameEventDurations   map[string]*DurationStats `protobuf:"bytes,4,rep,name=game_event_durations,json=gameEventDurations,proto3" json:"game_event_durations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MatchStatsCollection) Reset()         { *m = MatchStatsCollection{} }
func (m *MatchStatsCollection) String() string { return proto.CompactTextString(m) }
func (*MatchStatsCollection) ProtoMessage()    {}
func (*MatchStatsCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_21b017991eb90546, []int{6}
}

func (m *MatchStatsCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchStatsCollection.Unmarshal(m, b)
}
func (m *MatchStatsCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchStatsCollection.Marshal(b, m, deterministic)
}
func (m *MatchStatsCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchStatsCollection.Merge(m, src)
}
func (m *MatchStatsCollection) XXX_Size() int {
	return xxx_messageInfo_MatchStatsCollection.Size(m)
}
func (m *MatchStatsCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchStatsCollection.DiscardUnknown(m)
}

var xxx_messageInfo_MatchStatsCollection proto.InternalMessageInfo

func (m *MatchStatsCollection) GetMatchStats() []*MatchStats {
	if m != nil {
		return m.MatchStats
	}
	return nil
}

func (m *MatchStatsCollection) GetTeamStats() map[string]*TeamStats {
	if m != nil {
		return m.TeamStats
	}
	return nil
}

func (m *MatchStatsCollection) GetGamePhaseDurations() map[string]*DurationStats {
	if m != nil {
		return m.GamePhaseDurations
	}
	return nil
}

func (m *MatchStatsCollection) GetGameEventDurations() map[string]*DurationStats {
	if m != nil {
		return m.GameEventDurations
	}
	return nil
}

func init() {
	proto.RegisterEnum("TeamColor", TeamColor_name, TeamColor_value)
	proto.RegisterEnum("CommandType", CommandType_name, CommandType_value)
	proto.RegisterEnum("StageType", StageType_name, StageType_value)
	proto.RegisterEnum("GamePhaseType", GamePhaseType_name, GamePhaseType_value)
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterType((*GamePhase)(nil), "GamePhase")
	proto.RegisterType((*GameEventTimed)(nil), "GameEventTimed")
	proto.RegisterType((*TeamStats)(nil), "TeamStats")
	proto.RegisterType((*DurationStats)(nil), "DurationStats")
	proto.RegisterType((*MatchStats)(nil), "MatchStats")
	proto.RegisterMapType((map[string]*DurationStats)(nil), "MatchStats.GameEventDurationsEntry")
	proto.RegisterMapType((map[string]*DurationStats)(nil), "MatchStats.GamePhaseDurationsEntry")
	proto.RegisterType((*MatchStatsCollection)(nil), "MatchStatsCollection")
	proto.RegisterMapType((map[string]*DurationStats)(nil), "MatchStatsCollection.GameEventDurationsEntry")
	proto.RegisterMapType((map[string]*DurationStats)(nil), "MatchStatsCollection.GamePhaseDurationsEntry")
	proto.RegisterMapType((map[string]*TeamStats)(nil), "MatchStatsCollection.TeamStatsEntry")
}

func init() { proto.RegisterFile("ssl_match_stats.proto", fileDescriptor_21b017991eb90546) }

var fileDescriptor_21b017991eb90546 = []byte{
	// 1587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xc9, 0x72, 0xe3, 0x46,
	0x12, 0x1d, 0x6e, 0x12, 0x91, 0x24, 0x48, 0xa8, 0x24, 0x8d, 0xd8, 0xea, 0x9e, 0x19, 0x36, 0xbb,
	0x3b, 0x46, 0xa3, 0x1e, 0x51, 0x6e, 0x79, 0x09, 0x6f, 0x17, 0x88, 0x0d, 0x2d, 0x16, 0xb7, 0x28,
	0x42, 0xd1, 0xee, 0x13, 0x02, 0x22, 0x4b, 0x14, 0xa3, 0x01, 0x82, 0x01, 0x14, 0x25, 0xea, 0xe6,
	0x9f, 0xb0, 0xbf, 0xc0, 0x27, 0x7f, 0x83, 0x6f, 0xfe, 0x0f, 0x7f, 0x8b, 0xa3, 0x16, 0x6c, 0x94,
	0x18, 0xb6, 0xc3, 0x27, 0xdf, 0xaa, 0xf2, 0x65, 0x26, 0x32, 0x5f, 0x66, 0x56, 0x92, 0xb0, 0x1d,
	0x04, 0x8e, 0xe5, 0xda, 0x74, 0x78, 0x63, 0x05, 0xd4, 0xa6, 0x41, 0x73, 0xe6, 0x7b, 0xd4, 0xdb,
	0xfd, 0x66, 0x3c, 0xa1, 0x37, 0xf3, 0xab, 0xe6, 0xd0, 0x73, 0x0f, 0xb1, 0x77, 0xe5, 0xb5, 0xe6,
	0xb3, 0x83, 0xc1, 0xa0, 0x7d, 0x18, 0x04, 0xce, 0xc1, 0xd8, 0x3b, 0xa0, 0x9e, 0xe7, 0x04, 0x87,
	0xb3, 0x0f, 0x63, 0x26, 0xe0, 0x16, 0xec, 0x60, 0x8d, 0x6d, 0x97, 0x58, 0xe4, 0x96, 0x4c, 0xa9,
	0x75, 0xf4, 0xd1, 0x9b, 0x2f, 0x84, 0xaf, 0x06, 0x86, 0xf5, 0x96, 0xe7, 0xba, 0xf6, 0x74, 0x84,
	0xea, 0x90, 0xa7, 0xf7, 0x33, 0x52, 0xcb, 0xd4, 0x33, 0x7b, 0x95, 0xa3, 0x72, 0x53, 0xca, 0xcd,
	0xfb, 0x19, 0xc1, 0x1c, 0x41, 0xaf, 0xa0, 0x78, 0xed, 0xf9, 0x16, 0x25, 0xb6, 0x5b, 0xcb, 0x72,
	0x2d, 0x68, 0x9a, 0xc4, 0x76, 0x5b, 0x9e, 0xe3, 0xf9, 0x78, 0xfd, 0xda, 0xf3, 0xd9, 0xad, 0xf1,
	0x63, 0x01, 0x94, 0x53, 0xdb, 0x25, 0xfd, 0x1b, 0x3b, 0x20, 0xe8, 0x5f, 0x00, 0x01, 0xb5, 0x7d,
	0x6a, 0xd1, 0x89, 0x2b, 0x9c, 0xe7, 0xb1, 0xc2, 0x25, 0xe6, 0xc4, 0x25, 0xe8, 0x09, 0x14, 0xc9,
	0x74, 0x24, 0xc0, 0x2c, 0x07, 0xd7, 0xc9, 0x74, 0xc4, 0xa1, 0x5d, 0x28, 0x8e, 0xe6, 0xbe, 0x4d,
	0x27, 0xde, 0xb4, 0x96, 0xab, 0x67, 0xf6, 0x54, 0x1c, 0xdd, 0x51, 0x43, 0x06, 0x9b, 0xe7, 0x61,
	0x54, 0x9a, 0xd1, 0xf7, 0x12, 0xe1, 0x1e, 0x80, 0x3a, 0x14, 0x39, 0x58, 0x64, 0x4a, 0xfd, 0xfb,
	0x5a, 0xa1, 0x9e, 0xd9, 0x2b, 0x1d, 0x15, 0xc3, 0xcc, 0x70, 0x59, 0xc2, 0x06, 0x43, 0xd1, 0x6b,
	0x28, 0x47, 0xea, 0x8b, 0x09, 0xad, 0xad, 0x2d, 0x69, 0x97, 0x42, 0xed, 0xc5, 0x84, 0xa6, 0xa8,
	0x58, 0x5f, 0x49, 0x05, 0xfa, 0x0c, 0x36, 0x62, 0xde, 0x03, 0x19, 0x46, 0xb1, 0x9e, 0xdb, 0x2b,
	0x1d, 0x01, 0x8f, 0xd9, 0x60, 0x00, 0xae, 0x8e, 0xc3, 0x63, 0x20, 0x62, 0xf9, 0x04, 0xb4, 0x94,
	0x1d, 0x8b, 0x47, 0x79, 0x60, 0x56, 0x49, 0x98, 0xb1, 0xa0, 0xbe, 0x86, 0xed, 0x29, 0x59, 0x50,
	0x2b, 0x4c, 0x63, 0xe6, 0x7b, 0x33, 0x2f, 0x20, 0xa3, 0x1a, 0x2c, 0xa5, 0xb2, 0xc9, 0xd4, 0xe4,
	0xa5, 0x2f, 0x95, 0x50, 0x1d, 0x0a, 0x01, 0xb5, 0xc7, 0xa4, 0x56, 0x92, 0xf9, 0x0c, 0xd8, 0x8d,
	0xf3, 0x29, 0x00, 0xf4, 0x06, 0xb6, 0xf9, 0x81, 0x57, 0xcb, 0x72, 0xc8, 0x35, 0x95, 0x19, 0x95,
	0xeb, 0x99, 0xbd, 0x0d, 0x8c, 0x38, 0xc8, 0x4a, 0xd7, 0x26, 0xd7, 0x54, 0x24, 0x72, 0x08, 0x5b,
	0x0f, 0x4c, 0x58, 0x32, 0x2a, 0xb7, 0xd8, 0x48, 0x5b, 0xb0, 0x1c, 0x12, 0x55, 0x98, 0xf9, 0xe4,
	0xb6, 0x56, 0x59, 0x51, 0x85, 0xbe, 0x4f, 0x6e, 0xd1, 0x57, 0x69, 0x7a, 0xd9, 0x37, 0x46, 0xb5,
	0x2a, 0xe7, 0xa9, 0x1a, 0xf3, 0xc4, 0xfc, 0x8f, 0x92, 0x1c, 0x73, 0x41, 0xe3, 0x0e, 0x2a, 0x69,
	0x15, 0xf4, 0x3f, 0x80, 0xd8, 0x1d, 0x6f, 0xd5, 0x34, 0xdf, 0x4a, 0xe4, 0x02, 0x3d, 0x03, 0x85,
	0x7d, 0x2d, 0xa0, 0xb6, 0x3b, 0x93, 0x7d, 0x1b, 0x0b, 0x18, 0x7a, 0x37, 0xa1, 0x37, 0x23, 0xdf,
	0xbe, 0x13, 0xad, 0x5b, 0xc4, 0xb1, 0xa0, 0xf1, 0x7d, 0x1e, 0x14, 0xd6, 0x1d, 0x03, 0x36, 0xd3,
	0x08, 0x41, 0x7e, 0x6a, 0xcb, 0xc9, 0x50, 0x30, 0x3f, 0xa3, 0x2d, 0x28, 0x8c, 0x3d, 0xdb, 0x09,
	0xb8, 0x67, 0x15, 0x8b, 0x0b, 0x93, 0x5e, 0x7b, 0x73, 0x27, 0x90, 0xc3, 0x20, 0x2e, 0xe8, 0x39,
	0x94, 0xef, 0x89, 0xe3, 0x78, 0x77, 0xd6, 0xd0, 0xf6, 0x47, 0x01, 0x9f, 0x08, 0x15, 0x97, 0x84,
	0xac, 0xc5, 0x44, 0xe8, 0x29, 0x28, 0x3e, 0x19, 0x49, 0xbc, 0x20, 0x26, 0xc9, 0x27, 0x23, 0x01,
	0x3e, 0x87, 0x32, 0x0b, 0xdc, 0x9b, 0xcb, 0x09, 0x5d, 0x13, 0xf6, 0x52, 0xc6, 0x07, 0xf1, 0x15,
	0x54, 0xe4, 0x35, 0xb0, 0xa8, 0xfd, 0x81, 0x4c, 0x79, 0xcb, 0xab, 0x58, 0x0d, 0xa5, 0x26, 0x13,
	0xa2, 0x17, 0x10, 0x09, 0x78, 0xa5, 0x79, 0xed, 0x54, 0x1c, 0xba, 0x0f, 0x58, 0x8d, 0x51, 0x13,
	0x36, 0x67, 0x64, 0x6a, 0x3b, 0xf4, 0xde, 0x0a, 0x6e, 0x3c, 0xe6, 0xd0, 0xa3, 0xb6, 0x53, 0x2b,
	0x72, 0xd5, 0x0d, 0x09, 0x0d, 0x18, 0x62, 0x32, 0x00, 0x1d, 0xc1, 0x76, 0x5a, 0x3f, 0x98, 0x0f,
	0x87, 0x24, 0x08, 0x6a, 0x0a, 0xb7, 0xd8, 0x4c, 0x5a, 0x0c, 0x04, 0xc4, 0xe2, 0x1d, 0x7a, 0xd3,
	0x21, 0x19, 0x91, 0x91, 0x25, 0x78, 0x04, 0x11, 0x6f, 0x28, 0x3d, 0xe5, 0x7c, 0x36, 0x61, 0xf3,
	0xca, 0x76, 0x1c, 0x6b, 0xe6, 0xd8, 0x43, 0xe2, 0xb2, 0x87, 0x91, 0x13, 0x50, 0x12, 0xa1, 0x30,
	0xa8, 0x1f, 0x22, 0x9c, 0x86, 0xff, 0x42, 0x35, 0xad, 0x1f, 0xf0, 0xc6, 0x57, 0x71, 0x25, 0xa5,
	0x1b, 0xa0, 0x4f, 0x61, 0xc7, 0xb5, 0x17, 0x96, 0x3d, 0xa4, 0x93, 0x5b, 0x62, 0xa5, 0xaa, 0xa3,
	0x72, 0x83, 0x2d, 0xd7, 0x5e, 0xe8, 0x1c, 0x7d, 0x1f, 0x97, 0xa9, 0xf1, 0x5d, 0x16, 0xd4, 0xb7,
	0xf2, 0x81, 0x13, 0xbd, 0x91, 0x7c, 0x01, 0x33, 0x4b, 0x2f, 0xe0, 0x73, 0x28, 0x87, 0x67, 0xcb,
	0x9d, 0x4c, 0x65, 0xab, 0x94, 0x42, 0x59, 0x67, 0xb2, 0xa4, 0x62, 0x2f, 0x64, 0xdf, 0xc4, 0x2a,
	0xf6, 0x82, 0xe5, 0x14, 0xab, 0x90, 0xd1, 0xc4, 0x9e, 0xca, 0x06, 0xaa, 0x44, 0x5a, 0x5c, 0x9a,
	0xf2, 0x65, 0xdf, 0x8e, 0x65, 0x1b, 0x45, 0xbe, 0xf4, 0xdb, 0x31, 0x7a, 0x0d, 0x1b, 0x91, 0x8a,
	0x4f, 0x1c, 0x9b, 0xe5, 0xc7, 0xdb, 0x29, 0x8b, 0xb5, 0x10, 0xc0, 0x52, 0xce, 0x9a, 0x79, 0xe8,
	0xcd, 0xa7, 0x54, 0xb6, 0x92, 0xb8, 0x34, 0x7e, 0x28, 0x00, 0x74, 0xd8, 0xc2, 0x5b, 0x3d, 0x1b,
	0xaf, 0xa0, 0x22, 0x56, 0x62, 0xc4, 0x8c, 0xc8, 0x5c, 0xe5, 0xd2, 0x90, 0xbf, 0xa5, 0xb5, 0x03,
	0xcb, 0x6b, 0xe7, 0x35, 0x94, 0xf8, 0xa8, 0xcf, 0xd8, 0xce, 0x60, 0x13, 0x15, 0xbf, 0xad, 0x7c,
	0x8d, 0x60, 0xfe, 0x12, 0xf0, 0x63, 0xc0, 0x7c, 0x91, 0x05, 0xf5, 0x6d, 0xe1, 0x2b, 0x2f, 0xe6,
	0x99, 0x4b, 0xc2, 0x3d, 0x15, 0xdc, 0x78, 0x1e, 0xf5, 0xe6, 0x94, 0xd3, 0x52, 0xc4, 0xd1, 0x9d,
	0x2d, 0x00, 0xb6, 0x23, 0xc4, 0xfe, 0x96, 0xad, 0x20, 0x37, 0x8b, 0x58, 0x18, 0x3c, 0x51, 0x5c,
	0xa5, 0xe1, 0x51, 0x34, 0x04, 0x3a, 0x82, 0x6a, 0xc2, 0xee, 0xca, 0x99, 0x13, 0x4e, 0x54, 0xda,
	0x4a, 0x8d, 0xac, 0x8e, 0x9d, 0x39, 0x41, 0x97, 0xb0, 0x15, 0xe7, 0x14, 0xd1, 0x13, 0xc8, 0x7d,
	0xf3, 0xa2, 0x19, 0x13, 0x1b, 0xe7, 0x19, 0xf2, 0x25, 0xf6, 0x0e, 0x46, 0xe3, 0x07, 0x40, 0xe4,
	0x56, 0xfc, 0x76, 0x88, 0xdd, 0x2a, 0x8f, 0xbb, 0xe5, 0xef, 0xe3, 0x63, 0x6e, 0xd3, 0xc0, 0xee,
	0x25, 0xec, 0xac, 0x88, 0x02, 0x69, 0x90, 0xfb, 0x40, 0xee, 0x65, 0xd5, 0xd9, 0x11, 0xbd, 0x84,
	0xc2, 0xad, 0xcd, 0x48, 0xc8, 0x72, 0x12, 0x2a, 0xcd, 0xd4, 0x9c, 0x60, 0x01, 0x7e, 0x99, 0xfd,
	0x3c, 0x13, 0xba, 0x7d, 0x24, 0x8a, 0xbf, 0xe2, 0xb6, 0xf1, 0x4b, 0x1e, 0xb6, 0xe2, 0x44, 0x5b,
	0x9e, 0xe3, 0x90, 0x21, 0xef, 0xb3, 0xff, 0x43, 0x29, 0xf1, 0x0b, 0xad, 0x96, 0xe1, 0xa4, 0x94,
	0x12, 0xa4, 0x60, 0x70, 0xe3, 0x86, 0x6e, 0x01, 0xc4, 0x65, 0xad, 0x65, 0xb9, 0xf2, 0xcb, 0xe6,
	0x63, 0x8e, 0xe3, 0x32, 0x0b, 0x0a, 0x95, 0xa8, 0xd6, 0xc8, 0x5a, 0x51, 0x67, 0xd1, 0xc4, 0x07,
	0x8f, 0xbb, 0xfb, 0x33, 0x15, 0xb7, 0x56, 0x54, 0x3c, 0xff, 0x7b, 0x1f, 0xf8, 0xa3, 0xb5, 0x3f,
	0x83, 0x4a, 0x3a, 0xbd, 0x47, 0x6a, 0x53, 0x4f, 0xd7, 0x26, 0xd9, 0xf7, 0x0f, 0xcb, 0xfd, 0xf7,
	0xe8, 0xa2, 0xfd, 0xb6, 0x58, 0xfc, 0xfc, 0x47, 0x22, 0xd2, 0xa0, 0x6c, 0x1a, 0x7a, 0xc7, 0xba,
	0xec, 0x5e, 0x74, 0x7b, 0xef, 0xba, 0xda, 0x3f, 0x50, 0x15, 0x4a, 0x5c, 0xf2, 0xde, 0x68, 0xb7,
	0x7b, 0xef, 0xb4, 0x0c, 0x52, 0x41, 0xe1, 0x82, 0xe3, 0xf6, 0xa5, 0xa1, 0x65, 0xa3, 0x6b, 0xb7,
	0xd7, 0x35, 0xb4, 0xdc, 0xfe, 0x4f, 0x59, 0x28, 0x25, 0x7e, 0xa4, 0xa3, 0x4d, 0xa8, 0xb6, 0x7a,
	0x9d, 0x8e, 0xde, 0x7d, 0x9b, 0xf0, 0xa9, 0x41, 0x39, 0x14, 0x9e, 0xe9, 0x6d, 0x53, 0xcb, 0x24,
	0x25, 0x03, 0xb3, 0xd7, 0xd7, 0xb2, 0x68, 0x17, 0xfe, 0x19, 0x4a, 0x8e, 0xf5, 0x76, 0xdb, 0xea,
	0xb7, 0xf5, 0x96, 0xd1, 0x31, 0xba, 0xa6, 0x96, 0x43, 0x35, 0xd8, 0x0a, 0xb1, 0x6e, 0x0f, 0x77,
	0xf4, 0xb6, 0x35, 0x30, 0x75, 0x6c, 0x6a, 0x79, 0xb4, 0x03, 0x9b, 0x21, 0x72, 0xd2, 0xc3, 0x2d,
	0x43, 0x02, 0x85, 0x24, 0xf0, 0xf6, 0x1c, 0x1b, 0x2d, 0xd3, 0x3a, 0xc1, 0x86, 0xa1, 0xad, 0xa1,
	0x27, 0xb0, 0x1d, 0x02, 0xe7, 0xdd, 0x24, 0xb4, 0x8e, 0x9e, 0xc2, 0x4e, 0x08, 0xf5, 0xb1, 0xd1,
	0xd7, 0xb1, 0x61, 0x5d, 0x9c, 0xb7, 0x2e, 0x7a, 0x27, 0x27, 0x5a, 0xf1, 0x31, 0xb0, 0x6f, 0x74,
	0xf5, 0xb6, 0xf9, 0x5e, 0x53, 0x92, 0x59, 0x9b, 0xe7, 0x1d, 0xa3, 0x77, 0x69, 0x6a, 0x90, 0xcc,
	0xf1, 0xb4, 0xa7, 0xb7, 0xb5, 0xd2, 0xfe, 0xcf, 0x39, 0x50, 0xa2, 0x1f, 0xb4, 0x68, 0x03, 0xd4,
	0x81, 0xa9, 0x9f, 0x1a, 0x09, 0xa2, 0xfe, 0x03, 0x4f, 0x85, 0x48, 0xa6, 0x79, 0x72, 0x8e, 0x07,
	0x26, 0xe3, 0xec, 0x84, 0x7d, 0x54, 0xcb, 0xb0, 0x28, 0x56, 0x28, 0x08, 0x0a, 0x53, 0x20, 0xb7,
	0x63, 0xf1, 0x68, 0x39, 0x54, 0x87, 0x67, 0x29, 0x6c, 0x60, 0xb4, 0x7a, 0xa2, 0x1c, 0xc2, 0x75,
	0x1e, 0x3d, 0x83, 0xda, 0x2a, 0x0d, 0xad, 0x10, 0xfb, 0x36, 0xbe, 0x35, 0xb1, 0xce, 0xbd, 0x5a,
	0xc7, 0xd8, 0xd0, 0x2f, 0xb4, 0x35, 0xf4, 0x6f, 0xd8, 0x4d, 0x62, 0x4b, 0x41, 0xaf, 0x2f, 0xdb,
	0x26, 0x62, 0x2e, 0xb2, 0x72, 0x24, 0xb1, 0x38, 0x64, 0x25, 0x26, 0x43, 0x40, 0xcb, 0x11, 0x43,
	0x4c, 0xc6, 0x03, 0x05, 0xad, 0x14, 0x27, 0x2c, 0xab, 0x64, 0x0d, 0xce, 0x7a, 0x3d, 0xb3, 0x77,
	0x69, 0xca, 0xb0, 0xcb, 0x71, 0x58, 0xcb, 0x1a, 0x9a, 0xca, 0x0a, 0x2a, 0xb1, 0xde, 0xc0, 0xb4,
	0x4e, 0xf5, 0x8e, 0xa1, 0x55, 0xf6, 0x7f, 0xcd, 0x80, 0x9a, 0xfa, 0x8f, 0xc7, 0x4a, 0xd8, 0x3f,
	0xd3, 0x07, 0xc9, 0x12, 0x46, 0x22, 0x7c, 0xd9, 0xed, 0x9e, 0x77, 0x4f, 0xb5, 0x0c, 0xcb, 0x51,
	0x88, 0x96, 0xbb, 0x2a, 0xfb, 0x10, 0x0a, 0x7b, 0x2a, 0x87, 0x2a, 0x00, 0x02, 0xe2, 0x03, 0x92,
	0x67, 0x43, 0x20, 0xee, 0x4b, 0xe3, 0x51, 0x88, 0x3f, 0x19, 0xf6, 0xde, 0x1a, 0x9b, 0x62, 0xa9,
	0xcc, 0x93, 0x5d, 0x8f, 0xbd, 0xf1, 0x01, 0x2c, 0xb2, 0x04, 0xe5, 0x87, 0xa3, 0x04, 0x95, 0xab,
	0x35, 0xfe, 0x7f, 0xfc, 0xe3, 0xdf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xc7, 0x2a, 0x47, 0xf4,
	0x0f, 0x00, 0x00,
}
