version: 2.1

jobs:
  test_go:
    resource_class: medium
    docker:
      - image: cimg/go:1.26.1@sha256:ff658f9c1be3f51e1f4119b6fff3d874752f02173b8b2225c138afa1181d140e
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: go get -v -t -d ./...
      - run: go test -v -covermode=count -coverprofile=count.out ./...
      - run: go tool cover -html=count.out -o coverage.html
      - store_artifacts:
          path: coverage.html
          destination: coverage

workflows:
  version: 2
  build:
    jobs:
      - test_go
