version: 2.1

jobs:
  test_go:
    resource_class: medium
    docker:
      - image: cimg/go:1.26.1@sha256:f813931f2f093e96e4395d879d5785940242bd61567642362695e35592656af5
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: go get -v -t -d ./...
      - run: go test -v -covermode=count -coverprofile=count.out ./...
      - run: go tool cover -html=count.out -o coverage.html
      - store_artifacts:
          path: coverage.html
          destination: coverage

workflows:
  version: 2
  build:
    jobs:
      - test_go
